#!/usr/bin/env node
// Snapshot every source to the Wayback Machine, and record when.
//
// The link checker has already found four dead sources across this project's
// short life, and sixteen of the thirty-eight live ones sit on a single
// domain. A citation that 404s is not a citation, so this asks the Internet
// Archive to keep a copy and writes the snapshot date next to the URL.
//
//   node scripts/archive.mjs            # report what is and is not archived
//   node scripts/archive.mjs --save     # ask the Wayback Machine to snapshot
//
// Saving is opt-in because it makes real requests to somebody else's
// infrastructure, and it is rude to do that on every build.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { load } from '../lib/registry.mjs';
import { parseYaml } from '../lib/yaml.mjs';

const FILE = fileURLToPath(new URL('../data/archive.yml', import.meta.url));
const SAVE = process.argv.includes('--save');

const games = load();
const urls = new Map();
const note = (url, where) => {
  if (!/^https?:\/\//.test(String(url || ''))) return;
  if (!urls.has(url)) urls.set(url, []);
  urls.get(url).push(where);
};
for (const g of games) {
  for (const s of g.sources || []) note(s, g.slug);
  for (const r of g.rulings) {
    note(r.source, `${g.slug}/${r.id}`);
    for (const s of r.sources || []) note(s.url, `${g.slug}/${r.id}`);
  }
}

const existing = existsSync(FILE) ? parseYaml(readFileSync(FILE, 'utf8')).archived || [] : [];
const byUrl = new Map(existing.map((e) => [e.url, e]));

// Has the Wayback Machine got a copy, and how old is it?
async function lookup(url) {
  try {
    const res = await fetch(`https://archive.org/wayback/available?url=${encodeURIComponent(url)}`, {
      signal: AbortSignal.timeout(20000),
      headers: { 'user-agent': 'rulebook-archive/1.0 (+https://github.com/mohitagw15856/rulebook)' },
    });
    const j = await res.json();
    const snap = j?.archived_snapshots?.closest;
    return snap?.available ? { url: snap.url, timestamp: snap.timestamp } : null;
  } catch {
    return null;
  }
}

async function save(url) {
  try {
    const res = await fetch(`https://web.archive.org/save/${url}`, {
      method: 'GET',
      redirect: 'follow',
      signal: AbortSignal.timeout(60000),
      headers: { 'user-agent': 'rulebook-archive/1.0 (+https://github.com/mohitagw15856/rulebook)' },
    });
    return res.ok;
  } catch {
    return false;
  }
}

const fmt = (ts) => (ts ? `${ts.slice(0, 4)}-${ts.slice(4, 6)}-${ts.slice(6, 8)}` : null);

console.log(`\nChecking ${urls.size} sources against the Wayback Machine…\n`);
const out = [];
let have = 0;
let saved = 0;
let missing = 0;

for (const [url, where] of urls) {
  let snap = await lookup(url);

  if (!snap && SAVE) {
    process.stdout.write(`  archiving ${url} … `);
    const ok = await save(url);
    // The save endpoint is slow and rate-limited; give it a moment to land.
    if (ok) await new Promise((r) => setTimeout(r, 4000));
    snap = await lookup(url);
    console.log(snap ? 'done' : 'not yet — try again later');
    if (snap) saved++;
  }

  if (snap) {
    have++;
    out.push({ url, snapshot: snap.url, taken: fmt(snap.timestamp), cited_by: [...new Set(where)] });
    if (!SAVE) console.log(`  ✓ ${fmt(snap.timestamp)}  ${url}`);
  } else {
    missing++;
    out.push({ url, snapshot: null, taken: null, cited_by: [...new Set(where)] });
    console.log(`  ✗ no snapshot   ${url}`);
  }
}

const yaml =
  `# Generated by scripts/archive.mjs — do not edit by hand.\n` +
  `#\n` +
  `# A snapshot for every source, so a claim survives its citation going dead.\n` +
  `# Regenerate with: node scripts/archive.mjs --save\n\n` +
  `archived:\n` +
  out
    .map(
      (e) =>
        `  - url: ${e.url}\n` +
        (e.snapshot ? `    snapshot: ${e.snapshot}\n    taken: ${e.taken}\n` : `    snapshot: null\n`) +
        `    cited_by:\n${e.cited_by.map((c) => `      - ${c}`).join('\n')}\n`
    )
    .join('');
writeFileSync(FILE, yaml);

console.log(
  `\n${have} of ${urls.size} sources archived` +
    (saved ? `, ${saved} newly` : '') +
    (missing ? `, ${missing} with no snapshot` : '') +
    `.\n`
);
console.log(`  Written to data/archive.yml\n`);
if (missing && !SAVE) console.log(`  Run with --save to ask the Wayback Machine to take copies.\n`);
